"""empty message

Revision ID: 870daa1bacc9
Revises: 7e21ca0215af
Create Date: 2025-07-09 17:37:05.855034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870daa1bacc9'
down_revision = '7e21ca0215af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
